version: "3"

services:
  mongodb:
    image: mongo
    volumes:
      - db_volume:/data/db:rw
    ports:
      - 27017:27017
  backend:
    build: "./backend"
    ports: 
      - 10001
    depends_on:
      - mongodb
    environment:
      - DB_URL=mongodb://mongodb:27017
      - ROOT_PATH=/api
  frontend:
    image: nginx
    ports:
      - 12000:80
    volumes:
      - ./nginx_site.conf:/etc/nginx/conf.d/default.conf:ro
      - ./frontend/dist:/usr/share/nginx/html:ro
    depends_on:
      - backend
volumes:
  db_volume: